PIN-3673 Modified Party Registry Proxy
pagopa/interop-be-party-registry-proxy pull request #158
Opened 2023-07-26 09:42 UTC by nttdata-rtorsoli

2023-07-26 13:04 UTC, galales requested changes

2023-07-26 13:04 UTC, galales commented on src/main/scala/it/pagopa/interop/partyregistryproxy/service/impl/IPAOpenDataServiceImpl.scala
> +            .select[String]} - ${record(mapped(InstitutionsFields.agencyDescription)).select[String]}")
`.select[]` returns and `Option`. This string concatenation would result in the string
`Some(AOO name) - Some(Institution Name)`

2023-07-26 13:04 UTC, galales commented on src/main/scala/it/pagopa/interop/partyregistryproxy/service/impl/IPAOpenDataServiceImpl.scala
> +        Some(s"${record(mapped(InstitutionsFields.uoDescription))
same

2023-07-26 14:53 UTC, TonioGela approved these changes

2023-07-26 15:26 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/partyregistryproxy/service/impl/IPAOpenDataServiceImpl.scala
> +            .getOrElse("")} - ${record(mapped(InstitutionsFields.agencyDescription)).select[String].getOrElse("")}")
```suggestion
      case InstitutionKind.AOO    =>
        for {
          aoo    <- record(mapped(InstitutionsFields.aooDescription)).select[String]
          agency <- record(mapped(InstitutionsFields.agencyDescription)).select[String]
        } yield s"$aoo – $agency"
```

2023-07-26 15:26 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/partyregistryproxy/service/impl/IPAOpenDataServiceImpl.scala
> +            .getOrElse("")} - ${record(mapped(InstitutionsFields.agencyDescription)).select[String].getOrElse("")}")
```suggestion
      case InstitutionKind.UO     =>
        for {
          uo     <- record(mapped(InstitutionsFields.uoDescription)).select[String]
          agency <- record(mapped(InstitutionsFields.agencyDescription)).select[String]
        } yield s"$uo – $agency"
```

2023-07-26 15:27 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/partyregistryproxy/service/impl/util/DocumentConverter.scala
> +        },
```suggestion
       description = document.get(InstitutionField.DESCRIPTION.value),
```

2023-07-26 16:12 UTC, beetlecrunch approved these changes

2023-07-27 08:23 UTC, galales approved these changes

2023-07-27 14:08 UTC, merged